name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy Notebook
      run: |
        CONTENT=$(base64 -w 0 bronze_ingestion.ipynb)
        curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.0/workspace/import" \
        -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d "{
              \"path\": \"/Workspace/poc/bronze_ingestion\",
              \"format\": \"JUPYTER\",
              \"overwrite\": true,
              \"content\": \"$CONTENT\"
            }"

    - name: Run Job
      run: |
        curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.1/jobs/run-now" \
        -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d "{\"job_id\": ${{ secrets.JOB_ID }}}"
