name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install CLI
      run: pip install databricks-cli

    - name: Set Environment Variables ✅
      run: |
        echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
        echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

    - name: Debug Check ✅ (VERY IMPORTANT)
      run: |
        echo "HOST=$DATABRICKS_HOST"
        databricks workspace ls

    - name: Deploy Notebooks
      run: databricks workspace import_dir . /Workspace/poc --overwrite

    - name: Run Job
      run: databricks jobs run-now --job-id ${{ secrets.JOB_ID }}
